### PR TITLE
keeagent lifetime defaults to lifetime of entry in keepass

### PR DESCRIPTION
**Pull request by mrhoten**
Honor lifetime checkbox and lifetime duration when adding keeagent item to agent from keepass

### CODE REVIEW

**Comment by dlech** [comment]
Which lifetime checkbox are when honoring? What is the bug we are fixing? What are the steps to repeat this bug?

I tried out a few things and as far as I can tell, lifetime constrain is working.

**Comment by mrhoten** [comment]
Sorry, that text was terrible. Here are repro steps for the bug:

1. Have a keeagent entry in keepass, with the following properties:
-- "Add key to agent when database is opened" checkbox unchecked.
-- Confirm constraint checked
-- Lifetime constraint checked, with a non-default value of say 1800 seconds
2. Unlock the database
3. Tools | KeeAgent
4. Add... | From KeePass...
5. Select key from step (1), but do not hit OK

Result: Lifetime checkbox is unchecked
Expect: Lifetime checkbox should be checked, lifetime value should match step (1)
Note: Confirmation checkbox is checked, as expected.

6. Hit OK
Result 2: Lifetime checkbox is not checked in KeeAgent.
Expect: Lifetime checkbox checked to match key from step (1)

This PR changes the values of the UI in the "Add From Keepass" dialog box to honor the lifetime data in the keepass entry when importing it. This gives the user good feedback on the lifetime values (just like the user already gets on the confirmation checkbox). Then the rest of the code picks up the UI values and sets the properties of the key in the agent properly.

**Comment by dlech** [comment]
Makes total sense now. Thanks.

**Comment by dlech** [comment]
Thanks! Merged in b4bef082d649701ed9edbe44776e0a8997372b2b. I made one small style change (no space inside opening/closing parentheses).

**Pull request closed without merging**
