### PR TITLE
Add support for WSL sockets via AF_UNIX

### PR DESCRIPTION
**Pull request by mehrdadn**
Handles #220. Depends on dlech/SshAgentLib#14.

**Note 1:** Don't forget to update the submodule once dlech/SshAgentLib#14 is merged.

**Note 2:** Please perform a compatibility review before using this code. I only made these changes for my own personal use, and I may have paid insufficient attention to compatibility across different versions of Windows/.NET/etc. (though I'm hoping my check for `SocketError.AddressFamilyNotSupported` is sufficient to avoid breakage.)

### CODE REVIEW

**Comment by dlech** [comment]
I fixed a few small bugs and added a separate option for the WSL socket path in case people are using portable KeePass on both Windows and Linux.

**Comment by dlech** [comment]
https://github.com/dlech/KeeAgent/suites/5109170985/artifacts/153093059 is available for testing

**Comment by mehrdadn** [comment]
I started it and got "Failed to start Wsl socket: Value cannot be null. Parameter name: name".

I think you might want to set the default path to `%UserProfile%\.ssh\KeeAgent.wsl.sock`?

**Comment by dlech** [comment]
The could be because I changed the settings. You could try manually editing your keepass config xml file to remove all "Wsl" options and try again.

**Comment by mehrdadn** [comment]
Ah yeah, so when I clean the config, the option is disabled by default, and that problem doesn't occur anymore.

**Comment by dlech** [comment]
Cool. If everything else seems to be working, I'll go ahead and merge these.

**Comment by mehrdadn** [comment]
I SSH'ed with it fine, so I don't see any problems on my end!

**Comment by dlech** [comment]
Great, thanks!

**Pull request merged**
